server:
  port: 18081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=Asia/Shanghai